version: "2"


services:
    node-app:
       build: "."
       ports: 
          - "3000:3000"
       volumes:
          - .:/app
       links:
          - mongodb

    mongodb:
       image: "mongo:latest"



